name: Run Nightfall test suite

on:
  push:
    branches:
      - liju.jose/test-configure-github-actions-3

jobs:
  eslint-test:
    name: Run eslint check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.3'
      - run: npm ci
      - name: Run check for ESLint errors
        run: npm run lint

  zkp-unit-test-sha:
    name: ZKP microservice unit test (HASH_TYPE = sha)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.3'
      - name: Pull docker image
        run: |
          docker rmi $(docker images -aq)
          docker pull zokrates/zokrates:0.5.1
      - name: Increase swap memory
        run: |
          sudo usermod -a -G sudo runner
          sudo swapoff -a
          sudo fallocate -l 12G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
      - name: Build docker images
        run: docker-compose build
      - name: Generate the keys and constraint files for Zero Knowledge Proofs
        run: |
          chmod -R 777 zkp/code/
          npm run setupAll
      - name: Remove containers
        run: |
          docker stop $(docker ps -aq)
          docker rm $(docker ps -aq)
      - name: Deploy zkp contracts
        run: |
          docker-compose run --rm truffle-zkp compile --all
          docker-compose run --rm truffle-zkp migrate --reset --network=default
      - name: Run zkp unit tests
        run: docker-compose run --rm zkp npm test

  zkp-unit-test-mimc:
    name: ZKP microservice unit test (HASH_TYPE = mimc)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.3'
      - name: Pull docker image
        run: |
          docker rmi $(docker images -aq)
          docker pull zokrates/zokrates:0.5.1
      - name: Increase swap memory
        run: |
          sudo usermod -a -G sudo runner
          sudo swapoff -a
          sudo fallocate -l 12G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
      - name: Rename mimc docker-compose yml file
        run: |
          mv docker-compose.override.mimc.yml docker-compose.override.yml
      - name: Build docker images
        run: docker-compose build
      - name: Generate the keys and constraint files for Zero Knowledge Proofs
        run: |
          chmod -R 777 zkp/code/
          yes | docker-compose run zkp npm run setup-mimc -- -f ft-consolidation-transfer
      - name: Remove containers
        run: |
          docker stop $(docker ps -aq)
          docker rm $(docker ps -aq)
      - name: Deploy zkp contracts
        run: |
          docker-compose run --rm truffle-zkp compile --all
          docker-compose run --rm truffle-zkp migrate --reset --network=default
      - name: Run zkp unit tests
        run: docker-compose run --rm zkp node_modules/jest/bin/jest.js --verbose --runInBand --forceExit ./__tests__/mimc.js

  integration-test-sha:
    name: Run integration test (HASH_TYPE = sha)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.3'
      - name: Pull docker image
        run: |
          docker rmi $(docker images -aq)
          docker pull zokrates/zokrates:0.5.1
      - name: Increase swap memory
        run: |
          sudo usermod -a -G sudo runner
          sudo swapoff -a
          sudo fallocate -l 12G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
      - name: Build docker images
        run: docker-compose build
      - name: Generate the keys and constraint files for Zero Knowledge Proofs
        run: |
          chmod -R 777 zkp/code/
          npm run setupAll
      - name: Remove containers
        run: |
          docker stop $(docker ps -aq)
          docker rm $(docker ps -aq)
      - name: Run integration test
        run: ./nightfall-test
      - name: If integration test failed, upload logs files as artifacts
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: integration-test-logs
          path: nightfall_test.log

  integration-test-mimc:
    name: Run integration test (HASH_TYPE = mimc)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.3'
      - name: Pull docker image
        run: |
          docker rmi $(docker images -aq)
          docker pull zokrates/zokrates:0.5.1
      - name: Increase swap memory
        run: |
          sudo usermod -a -G sudo runner
          sudo swapoff -a
          sudo fallocate -l 12G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
      - name: Rename mimc docker-compose yml file
        run: mv docker-compose.override.mimc.yml docker-compose.override.yml
      - name: Build docker images
        run: docker-compose build
      - name: Generate the keys and constraint files for Zero Knowledge Proofs
        run: |
          chmod -R 777 zkp/code/
          npm run setupAll-mimc
      - name: Remove containers
        run: |
          docker stop $(docker ps -aq)
          docker rm $(docker ps -aq)
      - name: Run integration test
        run: ./nightfall-test
      - name: If integration test failed, upload logs files as artifacts
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: integration-test-logs
          path: nightfall_test.log
